preprocess_params:
  model: "huggingface"
  composers: "none"
  tokenizer: "ibm-granite/granite-3b-code-base"

inference_params :
    model: "granite-3b-code-base"
    seq_max_len: 2048
    input_data_path: ""
    context_max: -1

eval_params:
    device: cuda
