preprocess_params:
  model: "huggingface"
  composers: "none"
  tokenizer: "ibm-granite/granite-3b-code-instruct-128k"

inference_params :
    model: "granite-3b-code-instruct-128k"
    seq_max_len: 128000
    input_data_path: ""
    context_max: -1

eval_params:
    device: cuda
