preprocess_params:
  model: "huggingface"
  composers: "none"
  tokenizer: "ibm-granite/granite-34b-code-instruct"

inference_params :
    model: "granite-34b-code-instruct"
    seq_max_len: 8192
    input_data_path: ""
    context_max: -1

eval_params:
    device: cuda
