defaults:
  - params: codellama7b
  - composers_config: python_standard
  - dataset: small

language: 'python'

artifacts_dir: "data/code_generation/artifacts/"

wandb_project_name: 'LCA_context_composer_choice'

use_wandb: True

do_generation: True
seed: 42
wandb_project_name_generation: 'LCA_project_code_completion'

gpus: 1
composers: []